id: P7543F3BC
initial_creation_type: ocr
source_metadata:
  volumes:
    f6b0b4b4cd4a41b68701006196a018ad:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: སྐུ་དང་གསུང་དང་ཐུགས་རབ་ཏུ་གནས་པ།
      total_pages: 1953
      volume_number: 27
